# application.yml
openai:
  api:
    key: ${OPENAI_API_KEY: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} # Valeur par défaut pour le développement
    url: ${OPENAI_API_URL:https://openrouter.ai/api/v1/chat/completions}

rag:
  service:
    url: ${RAG_SERVICE_URL:http://rag-service:5000/query}



resilience4j:
  # Configuration du Circuit Breaker (existante)
  circuitbreaker:
    instances:
      ragService:
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        wait-duration-in-open-state: 10s
        sliding-window-type: TIME_BASED
        sliding-window-size: 10
      openaiService:
        failure-rate-threshold: 40
        minimum-number-of-calls: 5
        wait-duration-in-open-state: 30s

  # Ajoutez cette section (Nouveau)
  timelimiter:
    instances:
      ragService:
        timeout-duration: 40s  # Timeout spécifique pour RAG
      openaiService:
        timeout-duration: 70s  # Timeout plus long pour OpenAI