
services:
  mmysql:
    image: mysql:latest
    restart: always
    ports:
      - "3309:3306"
    environment:
      MYSQL_DATABASE: pfa_db
      MYSQL_USER: ayoub
      MYSQL_PASSWORD: ayoub
      MYSQL_ROOT_PASSWORD: root
      MYSQL_VALIDATE_PASSWORD: "OFF"
    volumes:
      - ./db/:/var/lib/mysql
    networks:
      - ai-conform-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 5

  spring-backend:
    build: ./pfa_uplaod
    command: ["./wait-for-mysql.sh", "java", "-jar", "app.jar"]
    restart: always
    expose:
      - "8080"
    environment:
      MYSQL_HOST: mmysql
      MYSQL_USER: ayoub
      MYSQL_PASSWORD: ayoub
      MYSQL_PORT: 3306
    networks:
      - ai-conform-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 3
    depends_on:
      mmysql:
        condition: service_healthy


  react-frontend:
    build: ./pfa_react
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - ai-conform-net

    environment:
      MYSQL_HOST: mmysql
      MYSQL_USER: ayoub
      MYSQL_PASSWORD: ayoub
      MYSQL_DATABASE: pfa_db
      MYSQL_PORT: 3306  

    depends_on:
      mmysql:
        condition: service_healthy
      spring-backend:
        condition: service_healthy
      rag-service:
        condition: service_healthy

  rag-service:
    build: ./rag_python
    command: ["./wait-for-mysql.sh", "python", "-m", "app.api"]
    ports:
      - "5000:5000"
    volumes:
      - ./rag_python/data:/app/data
    networks:
      - ai-conform-net
    environment:
      MYSQL_HOST: mmysql
      MYSQL_USER: ayoub
      MYSQL_PASSWORD: ayoub
      MYSQL_DATABASE: pfa_db
      MYSQL_PORT: 3306  
            
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:5000/health')"]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 120s
    depends_on:
      mmysql:
        condition: service_healthy

networks:
  ai-conform-net:
    driver: bridge

volumes:
  mysql_data:
    driver: local